version: '3'

services:
  db:
    image: postgres:16.2-bullseye
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - bridged

  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    networks:
      - bridged

networks:
  bridged:


volumes:
  db:
